version: "3.9"

services:
  ms-product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-product-service
    ports:
      - "8082:8080"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - shared-network
    depends_on:
      - config-server     # ✅ AÑADIDO
      - product-db

  product-db:
    image: postgres
    container_name: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"  # Evita conflicto si ya usas 5432 en otra parte
    networks:
      - shared-network
    volumes:
      - product-db-volume:/var/lib/postgresql/data

networks:
  shared-network:
    external: true

volumes:
  product-db-volume:
