version: "3.9"

services:
  discovery-service:
    container_name: discovery-service
    build: .
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - shared-network

networks:
  shared-network:
    external: true
